project_id = "bablutkomioidokmrmmr"

[functions.get-services]
verify_jwt = false

[functions.get-patients]
verify_jwt = false

[functions.add-patient]
verify_jwt = false

[functions.update-patient]
verify_jwt = false

[functions.check-availability]
verify_jwt = false

[functions.book-appointment]
verify_jwt = false